In [8]:
import numpy as np

data = np.arange(1, 21)
batch_size = 5

for i in range(0, len(data), batch_size):
    batch = data[i:i + batch_size]
    print(batch)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]
[16 17 18 19 20]
